#!/bin/bash
#Use this script to initialize the database for the first time
#use the command line argument "drop" to undo everything that this script does
UP=$(pgrep mysql | wc -l);
if [ "$UP" -ne 1 ];
then
       echo "MySQL is down. Starting up...";
       mysql.server start

else
       echo "MySQL is up.";
fi

if [ $# -eq 0 ]; then

   mysql -u root -e 'create user 'sub'@'localhost' identified by "123456";'
   mysql -u root -e 'GRANT CREATE ROUTINE, CREATE VIEW, ALTER, SHOW VIEW, CREATE, ALTER ROUTINE, EVENT, INSERT, SELECT, DELETE, TRIGGER, REFERENCES, UPDATE, DROP, EXECUTE, LOCK TABLES, CREATE TEMPORARY TABLES, INDEX ON tipsyswift.* TO 'sub'@'localhost';'
   echo "Reminder that MySQL is currently running. "
   echo "Please remember to stop MySQL when you are finished with mysql.server stop"
else
   if [ $1 = "drop" ]; then
       mysql -u root -e 'drop database tipsyswift;'
       mysql -u root -e 'drop user sub@localhost;'
       mysql.server stop
   fi
fi